name: EmoFilm
data:
  datasets:
    EmoFilm:
      path: datasets/EmoFilm/corpus.yaml
  remove_groups:
    language:
      keep:
      - es
  features: wav2vec_c_mean
model:
  type: null
eval:
  cv:
    part: film
    kfold: 5
  inner_kfold: 2
  inner_part: film
