name: MSP-IMPROV_4class
data:
  datasets:
    MSP-IMPROV:
      path: datasets/MSP-IMPROV/corpus.yaml
      subset: 4class
  features: wav2vec_c_mean
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: session
    kfold: -1
  inner_kfold: 2
  inner_part: session
