name: CREMA-D
data:
  datasets:
    CREMA-D:
      path: datasets/CREMA-D/corpus.yaml
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - neutral
      - sadness
  features: wav2vec_c_mean
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker
    kfold: 10
  inner_kfold: 2
  inner_part: speaker
