name: default
data:
  datasets:
    VENEC:
      path: papers/venec_cross_culture/VENEC_full/corpus.yaml
      features: null
      read_kwargs: {}
      subset: all
      map_groups: {}
      remove_groups: {}
      rename_annotations: {}
      select: null
      clip_seq: null
      pad_seq: null
  features: wav2vec_c_mean
  label: null
  map_groups:
    country:
      map:
        AUS: au
        IND: in
        KEN: ke
        SIN: sg
        USA: us
  remove_groups:
    label:
      drop:
      - neutral
      keep: []
  select: null
  clip_seq: null
  pad_seq: null
model:
  type: sk/lr
  config: null
  args: {}
  args_path: null
  param_grid: {}
  param_grid_path: null
eval:
  cv: null
  train:
    subset: ''
    groups:
      country:
        drop: []
        keep:
        - us
  valid:
    subset: ''
    groups:
      country:
        drop: []
        keep:
        - us
  test:
    subset: ''
    groups:
      country:
        drop: []
        keep:
        - sg
  inner_kfold: 2
  inner_part: null
evals: {}
training:
  balanced: true
  reps: 1
  normalise: online
  transform: std
  seq_transform: global
  n_jobs: 1
  verbose: 0
  label: label
  sklearn: null
  pytorch: null
  tensorflow: null
results: ''
