data:
  datasets:
    ESD:
      path: datasets/ESD/corpus.yaml
      subset: all
  remove_groups:
    language:
      keep:
      - zh
  features: wav2vec_c_mean
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  train:
    subset: train
  valid:
    subset: evaluation
  test:
    subset: test
