name: default
data:
  datasets:
    ShEMO:
      path: datasets/ShEMO/corpus.yaml
      features: null
      read_kwargs: {}
      subset: default
      map_groups: {}
      remove_groups: {}
      rename_annotations: {}
      select: null
      clip_seq: null
      pad_seq: null
    SAVEE:
      path: datasets/SAVEE/corpus.yaml
      features: null
      read_kwargs: {}
      subset: default
      map_groups: {}
      remove_groups: {}
      rename_annotations: {}
      select: null
      clip_seq: null
      pad_seq: null
  features: wav2vec_c_mean
  label: null
  map_groups: {}
  remove_groups:
    label:
      drop: []
      keep:
      - anger
      - happiness
      - sadness
  select: null
  clip_seq: null
  pad_seq: null
model:
  type: sk/lr
  config: null
  args: {}
  args_path: null
  param_grid: {}
  param_grid_path: null
eval:
  cv: null
  train:
    subset: ''
    groups:
      corpus:
        drop: []
        keep:
        - ShEMO
  valid:
    subset: ''
    groups:
      corpus:
        drop: []
        keep:
        - ShEMO
  test:
    subset: ''
    groups:
      corpus:
        drop: []
        keep:
        - SAVEE
  inner_kfold: 2
  inner_part: null
evals: {}
training:
  balanced: true
  reps: 1
  normalise: online
  transform: std
  seq_transform: global
  n_jobs: 1
  verbose: 0
  label: label
  sklearn: null
  pytorch: null
  tensorflow: null
results: ''
