name: CaFE
data:
  datasets:
    CaFE:
      path: datasets/CaFE/corpus.yaml
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
  features: wav2vec_c_mean
model:
  type: null
eval:
  cv:
    part: speaker
    kfold: 6
  inner_kfold: 2
  inner_part: speaker
