data:
  datasets:
    CMU-MOSEI:
      path: datasets/CMU-MOSEI/corpus.yaml
      subset: train_labels
      rename_annotations:
        label_plu: label
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
  features: wav2vec_c_mean
model:
  type: null
eval:
  cv:
    part: video
    kfold: 10
  inner_part: video
  inner_kfold: 2
