name: DEMoS
data:
  datasets:
    DEMoS:
      path: datasets/DEMoS/corpus.yaml
      subset: all
  remove_groups:
    prototypicality:
      drop:
        - NP
    label:
      keep:
      - anger
      - happiness
      - sadness
  features: wav2vec_c_mean
model:
  type: null
eval:
  cv:
    part: speaker
    kfold: 10
  inner_kfold: 2
  inner_part: speaker
