name: esd_zh_train
data:
  datasets:
    ESD_zh:
      path: datasets/ESD/corpus.yaml
      subset: train
  remove_groups:
    language:
      keep:
      - zh
    label:
      keep:
      - anger
      - happiness
      - sadness
  features: wav2vec_c_mean
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker
    kfold: 10
  inner_part: speaker
  inner_kfold: 2
