data:
  datasets:
    MELD:
      path: datasets/MELD/corpus.yaml
      subset: train
      map_groups:
        label:
          map:
            joy: happiness
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker
    kfold: 10
  inner_part: speaker
  inner_kfold: 2
