name: MESS
data:
  datasets:
    MESS:
      path: datasets/MESS/corpus.yaml
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
model:
  type: null
eval:
  cv:
    part: speaker
    kfold: -1
  inner_kfold: 2
  inner_part: speaker
