data:
  datasets:
    SUBESCO:
      path: datasets/SUBESCO/corpus.yaml
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker_name
    kfold: 10
  inner_kfold: 2
  inner_part: speaker_name
