data:
  datasets:
    TESS:
      path: datasets/TESS/corpus.yaml
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker
    kfold: -1
  inner_kfold: 2
