name: SAVEE
data:
  datasets:
    SAVEE:
      path: datasets/SAVEE/corpus.yaml
  remove_groups:
    label:
      keep:
        - anger
        - happiness
        - neutral
        - sadness
  features: wav2vec_c_mean
model:
  type: sk/lr
  config: ${cwdpath:conf/clf/sk/lr/default.yaml}
eval:
  cv:
    part: speaker
    kfold: -1
  inner_kfold: -1
  inner_part: speaker
