data:
  datasets:
    CMU-MOSEI:
      path: datasets/CMU-MOSEI/corpus.yaml
      subset: labels
      rename_annotations:
        label_plu: label
    MSP-PODCAST:
      path: datasets/MSP-PODCAST/corpus.yaml
      subset: all
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - sadness
      - fear
      - disgust
      - surprise
model:
  type: sk/lr
eval:
  train:
    groups:
      corpus:
        keep:
        - MSP-PODCAST
      split:
        keep:
        - Train
  valid:
    groups:
      corpus:
        keep:
        - MSP-PODCAST
      split:
        keep:
        - Validation
  test:
    groups:
      corpus:
        keep:
        - CMU-MOSEI
      split:
        keep:
        - test
  inner_kfold: 2
